### ISSUE TITLE
Unreachable code error on receiver

### ISSUE THREAD

**Issue by andrewwhitehead** [faern/oneshot#13]
Hiya,

I was doing some quick benchmarking on the oneshot and noticed that if you poll the Receiver once before the message is ready, then drop it, the thread panics with 'internal error: entered unreachable code'.

**Comment by faern** [comment]
Thanks for reporting this. I can reproduce it!

**Comment by faern** [comment]
Fixed and version `0.1.2` has been published. Hopefully this should solve your problem.

**Comment by andrewwhitehead** [comment]
Looks good, thanks!
