### ISSUE TITLE
Add into_raw() / from_raw() methods

### ISSUE THREAD

**Issue by bendk** [faern/oneshot#28]
Would you be open to adding `into_raw()` and `from_raw()` methods to convert between `Sender`/`Receiver` values and raw pointers?  I think `*mut ()` is correct, but any raw pointer is fine.

AFAICT, the underlying structs just store a pointer from `Box::into_raw` so this should be an easy to code.  I could probably open a PR if needed.  However, this does restrict what you can do with the structs in the future.

Use case: I'm a dev on the [UniFFI](https://github.com/mozilla/uniffi-rs/) project which generates FFI bindings for foreign languages.  I'm testing out using `oneshot` for async callback interface methods and so far it's working great, except when passing `Sender` across the FFI as a raw pointer.  My current code uses an extra `Box`, which isn't ideal given that `Sender` is already a wrapper around a leaked box pointer.

**Comment by faern** [comment]
I can't currently see any reason why from/into raw would be bad. I understand your use case and double boxing seem not ideal indeed!

Please submit a PR and we can discuss it from there

**Comment by faern** [comment]
Fixed in #29 and released as version [`0.1.6`](https://crates.io/crates/oneshot/0.1.6)
