### ISSUE TITLE
Sending the `Sender` instead of the `Receiver`

### ISSUE THREAD

**Issue by hellertime** [faern/oneshot#33]
I am interested in using this crate, but my use case is one where I'd like to construct the sender/receiver, and send the sender to another thread for it to send a message back to me. the problem is the sender is !Send... 

it looks like it should be OK to wrap the sender up in a struct that is Send and use this crate in a somewhat inverted manner, so long as I still only have a single sender and receiver. 

would you agree this is a safe use of the crate?

**Comment by Wuelle** [comment]
> the problem is the sender is !Send...

`Sender<T>` is `Send` as long as `T` is `Send`.  [^1]
https://github.com/faern/oneshot/blob/a67124caf71ccaa58269dca0b02c80caa985a6d9/src/lib.rs#L229-L230

If `T` isn't `Send` (which i assume is true in your case?) then you can't safely pass it between threads[^2] in the first place.

[^1]: https://docs.rs/oneshot/latest/oneshot/struct.Sender.html#impl-Send-for-Sender%3CT%3E)
[^2]: https://doc.rust-lang.org/nomicon/send-and-sync.html

**Comment by hellertime** [comment]
Oh right, but in my case I have a T that contains a Sender, and this seems to be causing an issue. 

For context, I am creating a ring-buffer between two threads, where I send over the buffer a request, containing a Sender so that the remote thread can send a reply. 

From what I gather out of the error, the NonNull channel_ptr, causes a Sender<T> where a T contains a Sender to be not send.

So I take it, if I wrapped the Sender inside the T, this would be OK.

**Comment by hellertime** [comment]
Ok. I think I may have been misinterpreting this error. I think its safe to close this.
