### ISSUE TITLE
add license files

### ISSUE THREAD

**Issue by solomoncyj** [faern/oneshot#48]
plse add the mit license and apache license into the repo and crate. thanks. Need them for packaging in fedora

**Comment by faern** [comment]
Ok! Fixed in https://github.com/faern/oneshot/commit/2d12377ff67b6721ad62eb57ff564ce09d661cf9

**Comment by solomoncyj** [comment]
oh, and remember to add them to cargo.toml!

**Comment by faern** [comment]
Why? The license is already explicitly stated in `Cargo.toml`. Can you point to some documentation that what you propose is best practice?

**Comment by LecrisUT** [comment]
Not adding them to `Cargo.toml`, just make sure they are in the `.crate` which should automatically be the case. Would be nice if you could exclude `check_mem_leaks.sh` (and maybe `.github`) though. Not crucial, it's just something that when packaging to Fedora we have to remove to avoid introducing an artificial dependency on `bash`.
